# Generated by Django 4.1.9 on 2023-06-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("zone_suffix", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("username", models.CharField(blank=True, max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("other_names", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True, unique=True)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, default="Same as Phone Number", max_length=255, null=True),
                ),
                ("company_name", models.CharField(blank=True, max_length=255, null=True)),
                ("nationality", models.CharField(blank=True, max_length=255, null=True)),
                ("drilling_licence", models.CharField(blank=True, max_length=255, null=True)),
                ("profession", models.CharField(blank=True, max_length=255, null=True)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                ("referee", models.CharField(blank=True, max_length=255, null=True)),
                ("referee_contact", models.CharField(blank=True, max_length=255, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                ("profile_complete", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.field"
                    ),
                ),
                (
                    "region_or_zone",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.zone"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
