# Generated by Django 4.1.9 on 2023-06-11 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_complete",
        ),
    ]
