# Generated by Django 4.1.9 on 2023-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_drilling_licence_user_drilling_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="declined",
            field=models.BooleanField(default=False),
        ),
    ]
