# Generated by Django 4.1.9 on 2023-05-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="declined",
            field=models.BooleanField(default=False),
        ),
    ]
