# Generated by Django 4.1.9 on 2023-06-03 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dues",
            name="month",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="dues",
            unique_together={("user", "month")},
        ),
    ]
