# Generated by Django 4.1.9 on 2023-06-08 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_uploadedfile_post_featured_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_Posted",
            new_name="date_posted",
        ),
    ]
