# Generated by Django 4.1.9 on 2023-06-08 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0004_rename_date_posted_post_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="forum.post"
            ),
        ),
    ]
